[package]
name = "oxidizr-arch-v2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oxidizr-arch-v2"
path = "src-2/main.rs"

[lib]
name = "oxidizr_arch_v2"
path = "src-2/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
env_logger = "0.11"
lazy_static = "1.4"
log = "0.4"
nix = { version = "0.29", features = ["user"] }
thiserror = "1.0"
which = "6.0"

[dev-dependencies]
tempfile = "3.10"

[profile.release]
opt-level = 3
lto = true
strip = true
